(define tree
'( (root 0 0 0)
    ( ("Alveolata" 2 2 0)
        ( ("environmental_samples" 1 1 0)
        )
        ( ("Ciliophora" 1 1 0)
            ( ("environmental_samples" 1 1 0)
            )
        )
    )
    ( ("Polycystinea" 1 1 0)
    )
    ( ("Metazoa" 1 1 0)
        ( ("Nematoda" 1 1 0)
            ( ("Chromadorea" 1 1 0)
                ( ("Tylenchida" 1 1 0)
                    ( ("Aphelenchoidea" 1 1 0)
                        ( ("Aphelenchidae" 1 1 0)
                            ( ("Aphelenchoides" 1 1 0)
                            )
                        )
                    )
                )
            )
        )
    )
    ( ("Cercozoa" 1 1 0)
        ( ("Heteromitidae" 1 1 0)
            ( ("Heteromita" 1 1 0)
            )
        )
    )
    ( ("Trimastix" 2 2 0)
    )
    ( ("Proleptomonas" 1 1 0)
    )
    ( ("Acanthamoebidae" 6 6 0)
        ( ("Acanthamoeba" 6 6 0)
            ( ("unclassified" 4 4 0)
                ( ("Acanthamoeba" 4 4 0)
                )
            )
        )
    )
    ( ("environmental_samples" 10 10 0)
    )
    ( ("Euglenozoa" 3 3 0)
        ( ("Kinetoplastida" 3 3 0)
            ( ("Bodonidae" 3 3 0)
                ( ("Dimastigella" 3 3 0)
                )
            )
        )
    )
    ( ("stramenopiles" 3 3 0)
        ( ("Bicosoecida" 3 3 0)
            ( ("unclassified" 3 3 0)
                ( ("Bicosoecida" 3 3 0)
                    ( ("Halocafeteria" 3 3 0)
                    )
                )
            )
        )
    )
    ( ("Fungi" 314 314 0)
        ( ("environmental_samples" 7 7 0)
        )
        ( ("Dikarya" 307 307 0)
            ( ("Basidiomycota" 35 35 0)
                ( ("environmental_samples" 1 1 0)
                )
                ( ("Agaricomycotina" 34 34 0)
                    ( ("Agaricomycetes" 1 1 0)
                        ( ("Agaricomycetidae" 1 1 0)
                            ( ("Agaricales" 1 1 0)
                                ( ("Strophariaceae" 1 1 0)
                                    ( ("Pholiota" 1 1 0)
                                    )
                                )
                            )
                        )
                    )
                    ( ("Tremellomycetes" 33 33 0)
                        ( ("Cystofilobasidiales" 33 33 0)
                            ( ("Cystofilobasidiaceae" 33 33 0)
                                ( ("Cystofilobasidium" 33 33 0)
                                )
                            )
                        )
                    )
                )
            )
            ( ("Ascomycota" 272 272 0)
                ( ("environmental_samples" 2 2 0)
                )
                ( ("Pezizomycotina" 6 6 0)
                    ( ("Eurotiomycetes" 1 1 0)
                        ( ("Eurotiomycetidae" 1 1 0)
                            ( ("Eurotiales" 1 1 0)
                                ( ("Trichocomaceae" 1 1 0)
                                    ( ("Eupenicillium" 1 1 0)
                                    )
                                )
                            )
                        )
                    )
                    ( ("Leotiomycetes" 1 1 0)
                        ( ("mitosporic" 1 1 0)
                            ( ("Leotiomycetes" 1 1 0)
                                ( ("Rhexocercosporidium" 1 1 0)
                                )
                            )
                        )
                    )
                    ( ("Sordariomycetes" 4 4 0)
                        ( ("Xylariomycetidae" 4 4 0)
                            ( ("Xylariales" 4 4 0)
                                ( ("Xylariaceae" 4 4 0)
                                    ( ("Xylaria" 3 3 0)
                                    )
                                    ( ("unclassified" 1 1 0)
                                        ( ("Xylariaceae" 1 1 0)
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
                ( ("mitosporic" 1 1 0)
                    ( ("Ascomycota" 1 1 0)
                        ( ("Engyodontium" 1 1 0)
                        )
                    )
                )
                ( ("Saccharomycotina" 80 80 0)
                    ( ("Saccharomycetes" 80 80 0)
                        ( ("Saccharomycetales" 80 80 0)
                            ( ("Saccharomycetaceae" 2 2 0)
                                ( ("Pichia" 2 2 0)
                                )
                            )
                            ( ("Dipodascaceae" 78 78 0)
                                ( ("Galactomyces" 78 78 0)
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)
)
