(define tree
'( (root 0 0 0)
    ( ("Beta" 4 0 0)
        ( ("Alcaligenaceae" 1 0 0)
            ( ("Alcaligenes_sp." 1 0 0)
            )
        )
        ( ("Burkholderia" 3 0 0)
            ( ("Burkholderia_sp." 3 0 0)
            )
        )
    )
    ( ("Actinobacteria" 12 0 0)
        ( ("Leifsonia" 1 0 0)
            ( ("Leifsonia_xyli." 1 0 0)
            )
        )
        ( ("Agromyces" 1 0 0)
            ( ("Agromyces_sp." 1 0 0)
            )
        )
        ( ("Rhodococcus" 10 0 0)
            ( ("Rhodococcus_sp." 5 0 0)
            )
            ( ("Rhodococcus_equi." 5 0 0)
            )
        )
    )
    ( ("Bacilli" 2 0 0)
        ( ("Staphylococcus" 1 0 0)
            ( ("Staphylococcus_sp." 1 0 0)
            )
        )
        ( ("Bacillus" 1 0 0)
            ( ("Bacillus_barbaricus" 1 0 0)
            )
        )
    )
    ( ("Gamma" 58 0 0)
        ( ("Buttiauxella" 1 0 0)
            ( ("Buttiauxella_gaviniae" 1 0 0)
            )
        )
        ( ("Erwinia" 1 0 0)
            ( ("Erwinia_sp." 1 0 0)
            )
        )
        ( ("Pseudomonas" 6 0 0)
            ( ("Pseudomonas_sp." 5 0 0)
            )
            ( ("Pseudomonas_rhizosphaerae" 1 0 0)
            )
        )
        ( ("Stenotrophomonas" 2 0 0)
            ( ("Stenotrophomonas_maltophilia" 2 0 0)
            )
        )
        ( ("Enterobacter" 7 0 0)
            ( ("Enterobacter_sp." 2 0 0)
            )
            ( ("Enterobacter_amnigenus" 5 0 0)
            )
        )
        ( ("Kluyvera" 2 0 0)
            ( ("Kluyvera_cochleae" 2 0 0)
            )
        )
        ( ("Rahnella" 14 0 0)
            ( ("Rahnella_sp." 14 0 0)
            )
        )
        ( ("Serratia" 25 0 0)
            ( ("Serratia_sp." 1 0 0)
            )
            ( ("Serratia_plymuthica" 10 0 0)
            )
            ( ("Serratia_proteamaculans" 14 0 0)
            )
        )
    )
    ( ("Alpha" 6 0 0)
        ( ("Pseudaminobacter" 1 0 0)
            ( ("Rhizobium_sp." 1 0 0)
            )
        )
        ( ("Rhizobium" 5 0 0)
            ( ("Agrobacterium_rhizogenes" 4 0 0)
            )
            ( ("Agrobacterium_tumefaciens" 1 0 0)
            )
        )
    )
)
)
