(define tree
'( (root 0 0 0)
    ( ("Fusobacteria" 2 2 0)
        ( ("Fusobacteria" 2 2 0)
            ( ("Fusobacteriales" 2 2 0)
                ( ("Fusobacteriaceae" 2 2 0)
                    ( ("Streptobacillus" 1 1 0)
                    )
                    ( ("Sneathia" 1 1 0)
                    )
                )
            )
        )
    )
    ( ("Planctomycetes" 2 2 0)
        ( ("Planctomycetacia" 2 2 0)
            ( ("Planctomycetales" 2 2 0)
                ( ("Planctomycetaceae" 2 2 0)
                    ( ("Isosphaera" 1 1 0)
                    )
                    ( ("Blastopirellula" 1 1 0)
                    )
                )
            )
        )
    )
    ( ("Bacteroidetes" 3 3 0)
        ( ("Bacteroidetes" 1 1 0)
            ( ("Bacteroidales" 1 1 0)
                ( ("Porphyromonadaceae" 1 1 0)
                    ( ("Tannerella" 1 1 0)
                    )
                )
            )
        )
        ( ("Sphingobacteria" 2 2 0)
            ( ("Sphingobacteriales" 2 2 0)
                ( ("Flexibacteraceae" 2 2 0)
                    ( ("Niastella" 1 1 0)
                    )
                    ( ("Spirosoma" 1 1 0)
                    )
                )
            )
        )
    )
    ( ("Actinobacteria" 1 1 0)
        ( ("Actinobacteria" 1 1 0)
            ( ("Actinobacteridae" 1 1 0)
                ( ("Bifidobacteriales" 1 1 0)
                    ( ("Bifidobacteriaceae" 1 1 0)
                        ( ("Gardnerella" 1 1 0)
                        )
                    )
                )
            )
        )
    )
    ( ("Firmicutes" 313 313 0)
        ( ("Bacilli" 23 23 0)
            ( ("Bacillales" 1 1 0)
                ( ("Sporolactobacillaceae" 1 1 0)
                    ( ("Sporolactobacillus" 1 1 0)
                    )
                )
            )
            ( ("Lactobacillales" 22 22 0)
                ( ("Carnobacteriaceae" 4 4 0)
                    ( ("Trichococcus" 4 4 0)
                    )
                )
                ( ("Leuconostocaceae" 18 18 0)
                    ( ("Leuconostoc" 2 2 0)
                    )
                    ( ("Weissella" 16 16 0)
                    )
                )
            )
        )
        ( ("Clostridia" 290 290 0)
            ( ("Clostridiales" 290 290 0)
                ( ("Peptostreptococcaceae" 1 1 0)
                    ( ("Gallicola" 1 1 0)
                    )
                )
                ( ("Acidaminococcaceae" 15 15 0)
                    ( ("Papillibacter" 2 2 0)
                    )
                    ( ("Propionispora" 6 6 0)
                    )
                    ( ("Anaerosinus" 7 7 0)
                    )
                )
                ( ("Clostridiaceae" 274 274 0)
                    ( ("Acetanaerobacterium" 1 1 0)
                    )
                    ( ("Anaerobacter" 5 5 0)
                    )
                    ( ("Subdoligranulum" 1 1 0)
                    )
                    ( ("Anaerotruncus" 40 40 0)
                    )
                    ( ("Clostridium" 65 65 0)
                    )
                    ( ("Ethanoligenens" 162 162 0)
                    )
                )
            )
        )
    )
    ( ("Proteobacteria" 52 52 0)
        ( ("Alphaproteobacteria" 14 14 0)
            ( ("Rhizobiales" 3 3 0)
                ( ("Hyphomicrobiaceae" 1 1 0)
                    ( ("Ancylobacter" 1 1 0)
                    )
                )
                ( ("Bradyrhizobiaceae" 2 2 0)
                    ( ("Bradyrhizobium" 2 2 0)
                    )
                )
            )
            ( ("Sphingomonadales" 11 11 0)
                ( ("Sphingomonadaceae" 11 11 0)
                    ( ("Erythromicrobium" 1 1 0)
                    )
                    ( ("Sphingobium" 2 2 0)
                    )
                    ( ("Sphingomonas" 5 5 0)
                    )
                    ( ("Novosphingobium" 3 3 0)
                    )
                )
            )
        )
        ( ("Betaproteobacteria" 5 5 0)
            ( ("Burkholderiales" 5 5 0)
                ( ("Burkholderiaceae" 2 2 0)
                    ( ("Wautersia" 1 1 0)
                    )
                    ( ("Burkholderia" 1 1 0)
                    )
                )
                ( ("Oxalobacteraceae" 3 3 0)
                    ( ("Naxibacter" 1 1 0)
                    )
                    ( ("Massilia" 2 2 0)
                    )
                )
            )
        )
        ( ("Gammaproteobacteria" 33 33 0)
            ( ("Xanthomonadales" 1 1 0)
                ( ("Xanthomonadaceae" 1 1 0)
                    ( ("Rhodanobacter" 1 1 0)
                    )
                )
            )
            ( ("Pseudomonadales" 3 3 0)
                ( ("Pseudomonadaceae" 3 3 0)
                    ( ("Pseudomonas" 3 3 0)
                    )
                )
            )
            ( ("Enterobacteriales" 29 29 0)
                ( ("Enterobacteriaceae" 29 29 0)
                    ( ("Buttiauxella" 1 1 0)
                    )
                    ( ("Buchnera" 1 1 0)
                    )
                    ( ("Leminorella" 1 1 0)
                    )
                    ( ("Obesumbacterium" 1 1 0)
                    )
                    ( ("Serratia" 1 1 0)
                    )
                    ( ("Enterobacter" 3 3 0)
                    )
                    ( ("Rahnella" 3 3 0)
                    )
                    ( ("Yersinia" 1 1 0)
                    )
                    ( ("Klebsiella" 5 5 0)
                    )
                    ( ("Erwinia" 3 3 0)
                    )
                    ( ("Citrobacter" 5 5 0)
                    )
                    ( ("Sodalis" 4 4 0)
                    )
                )
            )
        )
    )
)
)
