(define tree
'( (root 0 0 0)
    ( ("plant" 3 2 0)
        ( ("tree" 3 2 0)
            ( ("larch" 1 2 0)
            )
            ( ("maple" 2 0 0)
            )
        )
    )
    ( ("animal" 3 3 0)
        ( ("aardvark" 1 0 0)
        )
        ( ("moose" 1 0 0)
        )
        ( ("horse" 1 3 0)
        )
    )
)
)
