#!/bin/csh

alias nested-pie "mzscheme -r ../nested-pie.scm"

#set root="reclassification.5"
set root="reclassification.8"
set ambname="$root.amb"
set elevname="$root.elev"
set common_opts="-m 6  -f 12  -P"   # -P -m 3

nested-pie $common_opts amb $root. > $ambname.ps 
pstopdf $ambname.ps

nested-pie $common_opts -c 5 elev $root. > $elevname.ps 
pstopdf $elevname.ps

open -a Preview $ambname.pdf $elevname.pdf
#open -a Preview  $ambname.pdf
