(define tree
'( (root 0 0 0)
    ( ("SC4" 0 1 0)
        ( ("Unclassified" 0 1 0)
            ( ("otu_2698" 0 1 0)
            )
        )
    )
    ( ("OP10" 0 3 0)
        ( ("CH21" 0 3 0)
            ( ("otu_1736" 0 3 0)
            )
        )
    )
    ( ("OP3" 0 1 0)
        ( ("BD4-9" 0 1 0)
            ( ("otu_1769" 0 1 0)
            )
        )
    )
    ( ("Elev_16S_1860" 0 15 0)
        ( ("otu_986" 0 15 0)
        )
    )
    ( ("TM6" 1 2 0)
        ( ("otu_2808" 1 2 0)
        )
    )
    ( ("OP11" 2 4 0)
        ( ("Eub_2" 0 4 0)
            ( ("OPB92" 0 1 0)
                ( ("SM1F02" 0 1 0)
                    ( ("Unclassified" 0 1 0)
                        ( ("otu_1746" 0 1 0)
                        )
                    )
                )
            )
            ( ("WCHB1-56" 0 3 0)
                ( ("otu_1756" 0 3 0)
                )
            )
        )
        ( ("TA18" 2 0 0)
            ( ("J-1" 2 0 0)
                ( ("otu_1758" 2 0 0)
                )
            )
        )
    )
    ( ("SBR1093" 1 0 0)
        ( ("VHS-B5-50" 1 0 0)
            ( ("otu_2696" 1 0 0)
            )
        )
    )
    ( ("ZB2" 6 4 0)
        ( ("Unclassified" 0 1 0)
            ( ("otu_2868" 0 1 0)
            )
        )
        ( ("BD5-13" 2 0 0)
            ( ("otu_2873" 2 0 0)
            )
        )
        ( ("ABY1" 4 3 0)
            ( ("Unclassified" 0 2 0)
                ( ("otu_2869" 0 2 0)
                )
            )
            ( ("FW129" 4 1 0)
                ( ("KNA6-NB12" 0 1 0)
                    ( ("otu_2871" 0 1 0)
                    )
                )
                ( ("Unclassified" 4 0 0)
                    ( ("otu_2870" 4 0 0)
                    )
                )
            )
        )
    )
    ( ("Elusimicrobia" 1 0 0)
        ( ("vadinHB76" 1 0 0)
            ( ("Unclassified" 1 0 0)
                ( ("otu_989" 1 0 0)
                )
            )
        )
    )
    ( ("Cyanobacteria" 3 0 0)
        ( ("Chloroplasts" 2 0 0)
            ( ("Haslea" 1 0 0)
                ( ("otu_921" 1 0 0)
                )
            )
            ( ("Plant_chloroplast" 1 0 0)
                ( ("Unclassified" 1 0 0)
                    ( ("otu_923" 1 0 0)
                    )
                )
            )
        )
        ( ("mle1-12" 1 0 0)
            ( ("otu_936" 1 0 0)
            )
        )
    )
    ( ("WS3" 1 10 0)
        ( ("Sediment-1" 1 10 0)
            ( ("PRR-12" 1 10 0)
                ( ("otu_2862" 1 10 0)
                )
            )
        )
    )
    ( ("Firmicutes" 12 8 0)
        ( ("Clostridiaceae" 0 1 0)
            ( ("Unclassified" 0 1 0)
                ( ("otu_1158" 0 1 0)
                )
            )
        )
        ( ("Alicyclobacillaceae" 0 1 0)
            ( ("Alicyclobacillus" 0 1 0)
                ( ("Tumebacillus" 0 1 0)
                    ( ("otu_1036" 0 1 0)
                    )
                )
            )
        )
        ( ("Symbiobacteria" 2 0 0)
            ( ("Unclassified" 2 0 0)
                ( ("otu_1616" 2 0 0)
                )
            )
        )
        ( ("Acidaminococcaceae" 1 0 0)
            ( ("Unclassified" 1 0 0)
                ( ("otu_1004" 1 0 0)
                )
            )
        )
        ( ("Bacilli" 9 6 0)
            ( ("Bacillus_cereus_group" 0 1 0)
                ( ("Streptomyces" 0 1 0)
                    ( ("Bacillus_thuringiensis" 0 1 0)
                        ( ("Bacillus_cereus" 0 1 0)
                            ( ("Bacillus_pseudomycoides" 0 1 0)
                                ( ("otu_1050" 0 1 0)
                                )
                            )
                        )
                    )
                )
            )
            ( ("Paenibacillaceae" 1 4 0)
                ( ("Paenibacillus_alginolyticus" 0 2 0)
                    ( ("otu_1133" 0 2 0)
                    )
                )
                ( ("Unclassified" 1 2 0)
                    ( ("otu_1127" 1 2 0)
                    )
                )
            )
            ( ("Unclassified" 7 1 0)
                ( ("otu_1040" 7 1 0)
                )
            )
            ( ("Planococcaceae" 1 0 0)
                ( ("Unclassified" 1 0 0)
                    ( ("otu_1135" 1 0 0)
                    )
                )
            )
        )
    )
    ( ("Chlorobi" 3 1 0)
        ( ("SJA-28" 0 1 0)
            ( ("Unclassified" 0 1 0)
                ( ("otu_805" 0 1 0)
                )
            )
        )
        ( ("BSV19" 2 0 0)
            ( ("BSV26" 1 0 0)
                ( ("otu_787" 1 0 0)
                )
            )
            ( ("PK329" 1 0 0)
                ( ("otu_789" 1 0 0)
                )
            )
        )
        ( ("SM1H02" 1 0 0)
            ( ("otu_807" 1 0 0)
            )
        )
    )
    ( ("Chloroflexi" 32 49 0)
        ( ("Chloroflexi-4" 0 3 0)
            ( ("Unclassified" 0 3 0)
                ( ("otu_870" 0 3 0)
                )
            )
        )
        ( ("Unclassified" 1 0 0)
            ( ("otu_810" 1 0 0)
            )
        )
        ( ("Bljii12" 1 13 0)
            ( ("EB1097" 1 13 0)
                ( ("AKYG885" 0 2 0)
                    ( ("otu_867" 0 2 0)
                    )
                )
                ( ("B07_WMSP1" 1 11 0)
                    ( ("otu_868" 1 11 0)
                    )
                )
            )
        )
        ( ("Thermomicrobia" 3 0 0)
            ( ("Unclassified" 1 0 0)
                ( ("otu_897" 1 0 0)
                )
            )
            ( ("HN1-15" 2 0 0)
                ( ("PeM11" 2 0 0)
                    ( ("otu_899" 2 0 0)
                    )
                )
            )
        )
        ( ("TK17" 6 8 0)
            ( ("S085" 6 8 0)
                ( ("otu_902" 6 8 0)
                )
            )
        )
        ( ("Anaerolineae" 16 22 0)
            ( ("A4b" 0 1 0)
                ( ("Unclassified" 0 1 0)
                    ( ("otu_814" 0 1 0)
                    )
                )
            )
            ( ("H5" 0 2 0)
                ( ("otu_846" 0 2 0)
                )
            )
            ( ("SBR1031" 0 5 0)
                ( ("otu_853" 0 5 0)
                )
            )
            ( ("Unclassified" 0 1 0)
                ( ("otu_811" 0 1 0)
                )
            )
            ( ("Anaerolineales" 1 6 0)
                ( ("envOPS12" 0 4 0)
                    ( ("A30" 0 4 0)
                        ( ("otu_822" 0 4 0)
                        )
                    )
                )
                ( ("H39" 1 2 0)
                    ( ("otu_826" 1 2 0)
                    )
                )
            )
            ( ("A31" 2 3 0)
                ( ("S47" 2 3 0)
                    ( ("otu_813" 2 3 0)
                    )
                )
            )
            ( ("SOGA31" 13 4 0)
                ( ("otu_860" 13 4 0)
                )
            )
        )
        ( ("Ktedobacteria" 5 3 0)
            ( ("Ellin7237" 1 2 0)
                ( ("Unclassified" 0 2 0)
                    ( ("otu_892" 0 2 0)
                    )
                )
                ( ("AKAU3473" 1 0 0)
                    ( ("otu_893" 1 0 0)
                    )
                )
            )
            ( ("Ktedobacterales" 4 1 0)
                ( ("Unclassified" 4 1 0)
                    ( ("otu_894" 4 1 0)
                    )
                )
            )
        )
    )
    ( ("OD2" 6 17 0)
        ( ("candidate_division_OP11" 0 2 0)
            ( ("Unclassified" 0 2 0)
                ( ("otu_1724" 0 2 0)
                )
            )
        )
        ( ("Unclassified" 0 1 0)
            ( ("otu_1723" 0 1 0)
            )
        )
        ( ("SM2F11" 6 14 0)
            ( ("KNA6-NB23" 6 14 0)
                ( ("Elev_16S_1084" 6 14 0)
                    ( ("EV818EB5CPSAJJ44" 1 5 0)
                        ( ("otu_1733" 1 5 0)
                        )
                    )
                    ( ("Elev_16S_1619" 5 9 0)
                        ( ("otu_1732" 5 9 0)
                        )
                    )
                )
            )
        )
    )
    ( ("TM7" 2 24 0)
        ( ("TM7-1" 2 24 0)
            ( ("Elev_16S_424" 0 18 0)
                ( ("otu_2811" 0 18 0)
                )
            )
            ( ("Unclassified" 2 6 0)
                ( ("otu_2810" 2 6 0)
                )
            )
        )
    )
    ( ("Planctomycetes" 40 33 0)
        ( ("Anammoxales" 0 1 0)
            ( ("PK51" 0 1 0)
                ( ("otu_1806" 0 1 0)
                )
            )
        )
        ( ("agg27" 1 1 0)
            ( ("OM190" 0 1 0)
                ( ("ARKCH2Br2-76" 0 1 0)
                    ( ("otu_1798" 0 1 0)
                    )
                )
            )
            ( ("CL500-15" 1 0 0)
                ( ("B83" 1 0 0)
                    ( ("otu_1796" 1 0 0)
                    )
                )
            )
        )
        ( ("WPS-1" 7 9 0)
            ( ("Amsterdam-1B-07__BC20-1B-07" 0 2 0)
                ( ("otu_1862" 0 2 0)
                )
            )
            ( ("CL120-56" 1 1 0)
                ( ("CL500-3" 0 1 0)
                    ( ("HTA2" 0 1 0)
                        ( ("otu_1866" 0 1 0)
                        )
                    )
                )
                ( ("B86" 1 0 0)
                    ( ("otu_1864" 1 0 0)
                    )
                )
            )
            ( ("Ellin6207" 6 6 0)
                ( ("Planctomycetales" 6 6 0)
                    ( ("Planctomycetales_bacterium_Ellin6207" 6 6 0)
                        ( ("otu_1870" 6 6 0)
                        )
                    )
                )
            )
        )
        ( ("Planctomycetacia" 32 22 0)
            ( ("Isosphaerales" 2 0 0)
                ( ("Unclassified" 2 0 0)
                    ( ("otu_1818" 2 0 0)
                    )
                )
            )
            ( ("Pirellulales" 3 10 0)
                ( ("Pirellulaceae" 0 2 0)
                    ( ("otu_1842" 0 2 0)
                    )
                )
                ( ("Unclassified" 0 1 0)
                    ( ("otu_1822" 0 1 0)
                    )
                )
                ( ("p-1088-a5" 0 2 0)
                    ( ("Unclassified" 0 2 0)
                        ( ("otu_1834" 0 2 0)
                        )
                    )
                )
                ( ("A17" 3 5 0)
                    ( ("A25" 3 5 0)
                        ( ("otu_1824" 3 5 0)
                        )
                    )
                )
            )
            ( ("Plactomycetales" 7 5 0)
                ( ("H28" 0 1 0)
                    ( ("A24" 0 1 0)
                        ( ("Unclassified" 0 1 0)
                            ( ("otu_1856" 0 1 0)
                            )
                        )
                    )
                )
                ( ("DEL04" 0 4 0)
                    ( ("otu_1850" 0 4 0)
                    )
                )
                ( ("Unclassified" 7 0 0)
                    ( ("otu_1849" 7 0 0)
                    )
                )
            )
            ( ("Gemmatales" 20 7 0)
                ( ("RB512" 0 2 0)
                    ( ("UNNAMEABLE_1178613656" 0 2 0)
                        ( ("otu_1817" 0 2 0)
                        )
                    )
                )
                ( ("DEL56" 1 1 0)
                    ( ("Amb_16S_966" 1 1 0)
                        ( ("UNNAMEABLE_1178613745" 0 1 0)
                            ( ("otu_1812" 0 1 0)
                            )
                        )
                        ( ("Unclassified" 1 0 0)
                            ( ("otu_1811" 1 0 0)
                            )
                        )
                    )
                )
                ( ("Gemmata" 1 3 0)
                    ( ("Unclassified" 1 3 0)
                        ( ("otu_1813" 1 3 0)
                        )
                    )
                )
                ( ("Unclassified" 18 1 0)
                    ( ("otu_1809" 18 1 0)
                    )
                )
            )
        )
    )
    ( ("Gemmatimonadetes" 35 24 0)
        ( ("Gemm_2" 1 0 0)
            ( ("otu_1665" 1 0 0)
            )
        )
        ( ("Gemmatimonadetes" 34 24 0)
            ( ("Gemm-1b" 16 10 0)
                ( ("C1711WL" 5 1 0)
                    ( ("otu_1657" 5 1 0)
                    )
                )
                ( ("Unclassified" 11 9 0)
                    ( ("otu_1656" 11 9 0)
                    )
                )
            )
            ( ("Gemmatimonadales" 18 14 0)
                ( ("Unclassified" 1 8 0)
                    ( ("otu_1659" 1 8 0)
                    )
                )
                ( ("Ellin5301" 1 0 0)
                    ( ("otu_1661" 1 0 0)
                    )
                )
                ( ("N1423WL" 16 6 0)
                    ( ("otu_1664" 16 6 0)
                    )
                )
            )
        )
    )
    ( ("Bacteroidetes" 42 58 0)
        ( ("Sphingobacteriales" 0 1 0)
            ( ("Unclassified" 0 1 0)
                ( ("otu_752" 0 1 0)
                )
            )
        )
        ( ("b-17BO" 0 2 0)
            ( ("Unclassified" 0 2 0)
                ( ("otu_413" 0 2 0)
                )
            )
        )
        ( ("Saprospirales" 30 47 0)
            ( ("Saprospiraceae" 0 3 0)
                ( ("Haliscomenobacter" 0 1 0)
                    ( ("MS-Irr1-H" 0 1 0)
                        ( ("otu_742" 0 1 0)
                        )
                    )
                )
                ( ("Unclassified" 0 2 0)
                    ( ("otu_738" 0 2 0)
                    )
                )
            )
            ( ("DSBR-B012" 0 1 0)
                ( ("otu_732" 0 1 0)
                )
            )
            ( ("FukuN24" 0 19 0)
                ( ("Unclassified" 0 19 0)
                    ( ("otu_733" 0 19 0)
                    )
                )
            )
            ( ("FukuS23" 1 0 0)
                ( ("otu_737" 1 0 0)
                )
            )
            ( ("C15" 1 0 0)
                ( ("otu_729" 1 0 0)
                )
            )
            ( ("Terrimonaceae" 9 14 0)
                ( ("otu_747" 9 14 0)
                )
            )
            ( ("TSL-25" 4 2 0)
                ( ("otu_748" 4 2 0)
                )
            )
            ( ("Unclassified" 15 8 0)
                ( ("otu_726" 15 8 0)
                )
            )
        )
        ( ("Flavobacteriales" 8 4 0)
            ( ("PHOS-HE28" 1 0 0)
                ( ("otu_670" 1 0 0)
                )
            )
            ( ("Sporocytophaga" 7 4 0)
                ( ("Unclassified" 7 4 0)
                    ( ("otu_674" 7 4 0)
                    )
                )
            )
        )
        ( ("Flexibacterales" 4 4 0)
            ( ("Spirosomaceae" 1 0 0)
                ( ("otu_703" 1 0 0)
                )
            )
            ( ("PHOS-HE21" 2 4 0)
                ( ("C0108" 2 4 0)
                    ( ("Unclassified" 1 3 0)
                        ( ("otu_699" 1 3 0)
                        )
                    )
                    ( ("UNNAMEABLE_1178613742" 1 1 0)
                        ( ("otu_700" 1 1 0)
                        )
                    )
                )
            )
            ( ("Dyadobacter" 1 0 0)
                ( ("otu_694" 1 0 0)
                )
            )
        )
    )
    ( ("SPAM" 49 3 0)
        ( ("JG37-AG-121" 49 3 0)
            ( ("JG34-KF-252" 49 3 0)
                ( ("otu_2702" 49 3 0)
                )
            )
        )
    )
    ( ("Nitrospirae" 8 5 0)
        ( ("SDKAS1" 1 0 0)
            ( ("otu_1708" 1 0 0)
            )
        )
        ( ("Nitrospirales" 7 5 0)
            ( ("Nitrospiraceae" 7 5 0)
                ( ("Unclassified" 2 1 0)
                    ( ("otu_1704" 2 1 0)
                    )
                )
                ( ("Nitrospira" 5 4 0)
                    ( ("N_defluvii" 0 2 0)
                        ( ("otu_1706" 0 2 0)
                        )
                    )
                    ( ("Unclassified" 5 2 0)
                        ( ("otu_1705" 5 2 0)
                        )
                    )
                )
            )
        )
    )
    ( ("Verrucomicrobia" 69 38 0)
        ( ("Unclassified" 1 0 0)
            ( ("otu_2819" 1 0 0)
            )
        )
        ( ("Verrucomicrobiae" 1 0 0)
            ( ("Unclassified" 1 0 0)
                ( ("otu_2839" 1 0 0)
                )
            )
        )
        ( ("Verruco-3" 8 9 0)
            ( ("Verrucomicrobia_subdivision_3" 4 3 0)
                ( ("otu_2833" 4 3 0)
                )
            )
            ( ("Unclassified" 4 6 0)
                ( ("otu_2829" 4 6 0)
                )
            )
        )
        ( ("Opitutae" 5 1 0)
            ( ("Opitutaceae" 5 1 0)
                ( ("otu_2823" 5 1 0)
                )
            )
        )
        ( ("Spartobacteria" 54 28 0)
            ( ("Elev_16S_771" 1 2 0)
                ( ("otu_2827" 1 2 0)
                )
            )
            ( ("Unclassified" 53 26 0)
                ( ("otu_2826" 53 26 0)
                )
            )
        )
    )
    ( ("Proteobacteria" 415 469 0)
        ( ("Deltaproteobacteria" 31 28 0)
            ( ("Desulfobacteraceae" 0 2 0)
                ( ("Unclassified" 0 2 0)
                    ( ("otu_2559" 0 2 0)
                    )
                )
            )
            ( ("Syntrophobacteraceae" 0 1 0)
                ( ("Syntrophobacter" 0 1 0)
                    ( ("otu_2651" 0 1 0)
                    )
                )
            )
            ( ("Desulfuromonadales" 1 0 0)
                ( ("Geobacteraceae" 1 0 0)
                    ( ("Unclassified" 1 0 0)
                        ( ("otu_2602" 1 0 0)
                        )
                    )
                )
            )
            ( ("Bdellovibrionales" 1 3 0)
                ( ("CTD005-82B-02" 0 1 0)
                    ( ("otu_2550" 0 1 0)
                    )
                )
                ( ("Unclassified" 0 1 0)
                    ( ("otu_2538" 0 1 0)
                    )
                )
                ( ("Bdellovibrio" 1 1 0)
                    ( ("Bdellovibrio_bacteriovorus" 1 1 0)
                        ( ("otu_2547" 1 1 0)
                        )
                    )
                )
            )
            ( ("Unclassified" 1 1 0)
                ( ("otu_2535" 1 1 0)
                )
            )
            ( ("EB1021" 11 9 0)
                ( ("JG37-AG-128" 0 2 0)
                    ( ("otu_2611" 0 2 0)
                    )
                )
                ( ("JG37-AG-2" 2 1 0)
                    ( ("JG37-AG-55" 2 1 0)
                        ( ("otu_2613" 2 1 0)
                        )
                    )
                )
                ( ("H16" 1 1 0)
                    ( ("otu_2610" 1 1 0)
                    )
                )
                ( ("Unclassified" 1 5 0)
                    ( ("otu_2606" 1 5 0)
                    )
                )
                ( ("FW136" 7 0 0)
                    ( ("RCP2-54" 7 0 0)
                        ( ("RCP2-62" 7 0 0)
                            ( ("otu_2608" 7 0 0)
                            )
                        )
                    )
                )
            )
            ( ("Myxococcales" 17 12 0)
                ( ("Napoli-1B-37__BC07-1B-37" 0 1 0)
                    ( ("otu_2623" 0 1 0)
                    )
                )
                ( ("Unclassified" 1 1 0)
                    ( ("otu_2620" 1 1 0)
                    )
                )
                ( ("Myxococcus" 4 2 0)
                    ( ("otu_2622" 4 2 0)
                    )
                )
                ( ("Polyangiaceae" 12 8 0)
                    ( ("OM27" 0 1 0)
                        ( ("Unclassified" 0 1 0)
                            ( ("otu_2630" 0 1 0)
                            )
                        )
                    )
                    ( ("Polyangium" 4 4 0)
                        ( ("ZA3704c" 1 1 0)
                            ( ("Unclassified" 1 1 0)
                                ( ("otu_2635" 1 1 0)
                                )
                            )
                        )
                        ( ("Unclassified" 3 3 0)
                            ( ("otu_2634" 3 3 0)
                            )
                        )
                    )
                    ( ("Unclassified" 8 3 0)
                        ( ("otu_2624" 8 3 0)
                        )
                    )
                )
            )
        )
        ( ("AlphaBetaGammaproteobacteria" 384 441 0)
            ( ("OM60" 0 1 0)
                ( ("Unclassified" 0 1 0)
                    ( ("otu_2417" 0 1 0)
                    )
                )
            )
            ( ("Unclassified" 3 1 0)
                ( ("otu_1875" 3 1 0)
                )
            )
            ( ("Pseudomonadaceae" 3 1 0)
                ( ("Unclassified" 3 1 0)
                    ( ("otu_2452" 3 1 0)
                    )
                )
            )
            ( ("Legionellales" 4 5 0)
                ( ("Aquicella" 2 1 0)
                    ( ("otu_2384" 2 1 0)
                    )
                )
                ( ("Unclassified" 2 4 0)
                    ( ("otu_2381" 2 4 0)
                    )
                )
            )
            ( ("Alphaproteobacteria" 224 314 0)
                ( ("Labrys" 0 1 0)
                    ( ("alpha_proteobacterium_FH6" 0 1 0)
                        ( ("otu_2023" 0 1 0)
                        )
                    )
                )
                ( ("AKYG694" 0 62 0)
                    ( ("otu_1908" 0 62 0)
                    )
                )
                ( ("Nordella" 3 2 0)
                    ( ("Unclassified" 3 2 0)
                        ( ("otu_2028" 3 2 0)
                        )
                    )
                )
                ( ("Stappia" 1 0 0)
                    ( ("Unclassified" 1 0 0)
                        ( ("otu_2158" 1 0 0)
                        )
                    )
                )
                ( ("A20" 2 3 0)
                    ( ("otu_1890" 2 3 0)
                    )
                )
                ( ("Devosia" 3 2 0)
                    ( ("otu_2008" 3 2 0)
                    )
                )
                ( ("Acetobacterales" 2 6 0)
                    ( ("Roseococcaceae" 0 2 0)
                        ( ("Unclassified" 0 2 0)
                            ( ("otu_1903" 0 2 0)
                            )
                        )
                    )
                    ( ("Unclassified" 1 4 0)
                        ( ("otu_1891" 1 4 0)
                        )
                    )
                    ( ("Acidisphaera" 1 0 0)
                        ( ("otu_1896" 1 0 0)
                        )
                    )
                )
                ( ("Rhizobiales" 5 5 0)
                    ( ("Rhizobiaceae" 3 3 0)
                        ( ("Unclassified" 3 3 0)
                            ( ("otu_2056" 3 3 0)
                            )
                        )
                    )
                    ( ("Phyllobacteriaceae" 2 2 0)
                        ( ("Mesorhizobium" 2 2 0)
                            ( ("Sinorhizobium" 2 2 0)
                                ( ("Mesorhizobium_huakuii" 2 2 0)
                                    ( ("Unclassified" 2 2 0)
                                        ( ("otu_2053" 2 2 0)
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
                ( ("H4" 5 4 0)
                    ( ("H29" 5 4 0)
                        ( ("otu_2016" 5 4 0)
                        )
                    )
                )
                ( ("Ellin314" 11 18 0)
                    ( ("bacterium_Ellin328" 1 0 0)
                        ( ("otu_2010" 1 0 0)
                        )
                    )
                    ( ("bacterium_Ellin361" 6 6 0)
                        ( ("otu_2011" 6 6 0)
                        )
                    )
                    ( ("Unclassified" 4 12 0)
                        ( ("otu_2009" 4 12 0)
                        )
                    )
                )
                ( ("Rhodobacterales" 6 1 0)
                    ( ("HP1B78" 1 0 0)
                        ( ("otu_2071" 1 0 0)
                        )
                    )
                    ( ("Hyphomonadaceae" 1 0 0)
                        ( ("Hyphomonas" 1 0 0)
                            ( ("Unclassified" 1 0 0)
                                ( ("otu_2073" 1 0 0)
                                )
                            )
                        )
                    )
                    ( ("SM1D08" 4 1 0)
                        ( ("S36" 4 1 0)
                            ( ("otu_2106" 4 1 0)
                            )
                        )
                    )
                )
                ( ("Sphingomonadales" 14 17 0)
                    ( ("Porphyrobacter" 0 1 0)
                        ( ("Unclassified" 0 1 0)
                            ( ("otu_2128" 0 1 0)
                            )
                        )
                    )
                    ( ("Sphingomonas" 0 5 0)
                        ( ("Sphingomonadaceae" 0 3 0)
                            ( ("Unclassified" 0 1 0)
                                ( ("otu_2135" 0 1 0)
                                )
                            )
                            ( ("star-like_microcolonies" 0 1 0)
                                ( ("Sphingomonas_echinoides" 0 1 0)
                                    ( ("bacterium_AH76" 0 1 0)
                                        ( ("Pseudomonas_sp_RM2-2001" 0 1 0)
                                            ( ("otu_2143" 0 1 0)
                                            )
                                        )
                                    )
                                )
                            )
                            ( ("Sphingomonas_sp_Ant20" 0 1 0)
                                ( ("Sphingomonas_sp_M3C203B-B" 0 1 0)
                                    ( ("Unclassified" 0 1 0)
                                        ( ("otu_2138" 0 1 0)
                                        )
                                    )
                                )
                            )
                        )
                        ( ("Sphingomonas_sp_MK346" 0 2 0)
                            ( ("Sphingomonas_melonis" 0 2 0)
                                ( ("otu_2148" 0 2 0)
                                )
                            )
                        )
                    )
                    ( ("Sphingobium" 2 0 0)
                        ( ("Unclassified" 2 0 0)
                            ( ("otu_2131" 2 0 0)
                            )
                        )
                    )
                    ( ("Sphingomonas_sp_SIA181-1A1" 1 2 0)
                        ( ("Sphingomonas_sp_KAR7" 0 2 0)
                            ( ("otu_2154" 0 2 0)
                            )
                        )
                        ( ("Unclassified" 1 0 0)
                            ( ("otu_2153" 1 0 0)
                            )
                        )
                    )
                    ( ("Unclassified" 6 8 0)
                        ( ("otu_2123" 6 8 0)
                        )
                    )
                    ( ("AKAU3595" 5 1 0)
                        ( ("otu_2124" 5 1 0)
                        )
                    )
                )
                ( ("Ellin329" 18 21 0)
                    ( ("KF-JG30-B3" 3 2 0)
                        ( ("otu_2014" 3 2 0)
                        )
                    )
                    ( ("Unclassified" 6 4 0)
                        ( ("otu_2012" 6 4 0)
                        )
                    )
                    ( ("bacterium_Ellin332" 9 15 0)
                        ( ("otu_2013" 9 15 0)
                        )
                    )
                )
                ( ("Unclassified" 16 8 0)
                    ( ("otu_1889" 16 8 0)
                    )
                )
                ( ("Caulobacterales" 5 8 0)
                    ( ("Brevundimonas" 2 3 0)
                        ( ("Caulobacter" 1 3 0)
                            ( ("Caulobacter_henricii" 0 3 0)
                                ( ("Caulobacter_sp" 0 3 0)
                                    ( ("Caulobacter_vibrioides" 0 3 0)
                                        ( ("Caulobacter_crescentus_CB15" 0 3 0)
                                            ( ("Unclassified" 0 2 0)
                                                ( ("otu_1983" 0 2 0)
                                                )
                                            )
                                            ( ("glacier_bacterium_FXI47" 0 1 0)
                                                ( ("bacterium_BH98-202" 0 1 0)
                                                    ( ("otu_1985" 0 1 0)
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                            ( ("Unclassified" 1 0 0)
                                ( ("otu_1979" 1 0 0)
                                )
                            )
                        )
                        ( ("Caulobacteraceae" 1 0 0)
                            ( ("Asticcacaulis" 1 0 0)
                                ( ("Unclassified" 1 0 0)
                                    ( ("otu_1987" 1 0 0)
                                    )
                                )
                            )
                        )
                    )
                    ( ("Unclassified" 3 5 0)
                        ( ("otu_1977" 3 5 0)
                        )
                    )
                )
                ( ("Bradyrhizobiales" 133 156 0)
                    ( ("Methylobacteriaceae" 2 2 0)
                        ( ("Methylobacterium_nodulans" 0 1 0)
                            ( ("otu_1960" 0 1 0)
                            )
                        )
                        ( ("Unclassified" 2 1 0)
                            ( ("otu_1957" 2 1 0)
                            )
                        )
                    )
                    ( ("Gitt-KF-194" 12 1 0)
                        ( ("Amb_16S_1821" 12 1 0)
                            ( ("otu_1952" 12 1 0)
                            )
                        )
                    )
                    ( ("Beijerinckiaceae" 1 1 0)
                        ( ("DA067" 0 1 0)
                            ( ("otu_1917" 0 1 0)
                            )
                        )
                        ( ("Unclassified" 1 0 0)
                            ( ("otu_1916" 1 0 0)
                            )
                        )
                    )
                    ( ("WIM133" 2 0 0)
                        ( ("otu_1972" 2 0 0)
                        )
                    )
                    ( ("Uncl." 14 10 0)  ; Unclassified
                        ( ("otu_1914" 14 10 0)
                        )
                    )
                    ( ("LO133" 3 5 0)
                        ( ("otu_1956" 3 5 0)
                        )
                    )
                    ( ("Bradyrhizobium" 12 7 0)
                        ( ("Unclassified" 1 0 0)
                            ( ("otu_1919" 1 0 0)
                            )
                        )
                        ( ("Rhodopseudomonas" 11 7 0)
                            ( ("Unclassified" 1 0 0)
                                ( ("otu_1920" 1 0 0)
                                )
                            )
                            ( ("Bradyrhizobiaceae" 10 7 0)
                                ( ("Bradyrhizobium_sp_Tv2a-2" 3 0 0)
                                    ( ("otu_1949" 3 0 0)
                                    )
                                )
                                ( ("Afipia" 7 7 0)
                                    ( ("Unclassified" 1 3 0)
                                        ( ("otu_1922" 1 3 0)
                                        )
                                    )
                                    ( ("Blastobacter" 6 4 0)
                                        ( ("Rhizobium" 6 4 0)
                                            ( ("Agromonas" 6 4 0)
                                                ( ("Bradyrhizobium_japonicum" 6 4 0)
                                                    ( ("Rhodopseudomonas_palustris" 6 4 0)
                                                        ( ("Bradyrhizobium_japonicum_USDA_110" 6 4 0)
                                                            ( ("Bradyrhizobium_sp" 6 4 0)
                                                                ( ("Bradyrhizobium_lupini" 6 4 0)
                                                                    ( ("Bradyrhizobium_genosp_G" 1 0 0)
                                                                        ( ("Unclassified" 1 0 0)
                                                                            ( ("otu_1945" 1 0 0)
                                                                            )
                                                                        )
                                                                    )
                                                                    ( ("Unclassified" 5 4 0)
                                                                        ( ("otu_1930" 5 4 0)
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                    ( ("Hyphomicrobiaceae2" 6 10 0)
                        ( ("Hyphomicrobium" 0 1 0)
                            ( ("Unclassified" 0 1 0)
                                ( ("otu_1954" 0 1 0)
                                )
                            )
                        )
                        ( ("Hyphomicrobium_denitrificans" 4 1 0)
                            ( ("otu_1955" 4 1 0)
                            )
                        )
                        ( ("Unclassified" 2 8 0)
                            ( ("otu_1953" 2 8 0)
                            )
                        )
                    )
                    ( ("Rhodoplanaceae" 81 120 0)
                        ( ("Elev_16S_1075" 0 24 0)
                            ( ("otu_1969" 0 24 0)
                            )
                        )
                        ( ("Elev_16S_835" 2 32 0)
                            ( ("otu_1970" 2 32 0)
                            )
                        )
                        ( ("Amb_16S_586" 12 1 0)
                            ( ("otu_1968" 12 1 0)
                            )
                        )
                        ( ("Amb_16S_442" 22 5 0)
                            ( ("otu_1967" 22 5 0)
                            )
                        )
                        ( ("Unclassified" 45 58 0)
                            ( ("otu_1966" 45 58 0)
                            )
                        )
                    )
                )
            )
            ( ("Ellin339" 15 14 0)
                ( ("pLW-30" 0 2 0)
                    ( ("otu_2332" 0 2 0)
                    )
                )
                ( ("Unclassified" 15 12 0)
                    ( ("otu_2331" 15 12 0)
                    )
                )
            )
            ( ("Betaproteobacteria" 117 101 0)
                ( ("Neisseriales" 0 1 0)
                    ( ("Neisseria" 0 1 0)
                        ( ("Rhodovibrio" 0 1 0)
                            ( ("Rhodovibrio_sp_2Mb1" 0 1 0)
                                ( ("Unclassified" 0 1 0)
                                    ( ("otu_2291" 0 1 0)
                                    )
                                )
                            )
                        )
                    )
                )
                ( ("Rhodocyclales" 1 2 0)
                    ( ("Unclassified" 1 2 0)
                        ( ("otu_2300" 1 2 0)
                        )
                    )
                )
                ( ("Methylophilales" 2 1 0)
                    ( ("otu_2277" 2 1 0)
                    )
                )
                ( ("Unclassified" 1 3 0)
                    ( ("otu_2177" 1 3 0)
                    )
                )
                ( ("SBR1001" 4 2 0)
                    ( ("Unclassified" 4 2 0)
                        ( ("otu_2317" 4 2 0)
                        )
                    )
                )
                ( ("A21b" 28 21 0)
                    ( ("EB1018" 10 5 0)
                        ( ("otu_2179" 10 5 0)
                        )
                    )
                    ( ("Unclassified" 18 16 0)
                        ( ("otu_2178" 18 16 0)
                        )
                    )
                )
                ( ("Burkholderiales" 57 39 0)
                    ( ("Alcaligenaceae" 0 1 0)
                        ( ("Alcaligenes" 0 1 0)
                            ( ("Unclassified" 0 1 0)
                                ( ("otu_2182" 0 1 0)
                                )
                            )
                        )
                    )
                    ( ("Comamonadaceae" 19 16 0)
                        ( ("Unclassified" 7 5 0)
                            ( ("otu_2203" 7 5 0)
                            )
                        )
                        ( ("Comamonas" 12 11 0)
                            ( ("T20" 0 6 0)
                                ( ("otu_2236" 0 6 0)
                                )
                            )
                            ( ("Rhodoferax" 6 0 0)
                                ( ("T3" 1 0 0)
                                    ( ("Unclassified" 1 0 0)
                                        ( ("otu_2234" 1 0 0)
                                        )
                                    )
                                )
                                ( ("Unclassified" 5 0 0)
                                    ( ("otu_2232" 5 0 0)
                                    )
                                )
                            )
                            ( ("Variovorax" 3 5 0)
                                ( ("Variovorax_sp_WFF52" 3 5 0)
                                    ( ("Variovorax_paradoxus" 3 5 0)
                                        ( ("Variovorax_sp_HAB-30" 3 5 0)
                                            ( ("Unclassified" 0 1 0)
                                                ( ("otu_2241" 0 1 0)
                                                )
                                            )
                                            ( ("Variovorax_sp_Pal2" 3 4 0)
                                                ( ("Unclassified" 0 3 0)
                                                    ( ("otu_2242" 0 3 0)
                                                    )
                                                )
                                                ( ("Variovorax_sp_3A_12" 3 1 0)
                                                    ( ("otu_2243" 3 1 0)
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                            ( ("Unclassified" 3 0 0)
                                ( ("otu_2204" 3 0 0)
                                )
                            )
                        )
                    )
                    ( ("Burkholderiaceae" 11 0 0)
                        ( ("Burkholderia" 11 0 0)
                            ( ("Burkholderia_phymatum" 2 0 0)
                                ( ("otu_2198" 2 0 0)
                                )
                            )
                            ( ("Unclassified" 5 0 0)
                                ( ("otu_2195" 5 0 0)
                                )
                            )
                            ( ("Burkholderia_sp_A633GD" 1 0 0)
                                ( ("otu_2201" 1 0 0)
                                )
                            )
                            ( ("Burkholderia_sp" 3 0 0)
                                ( ("Unclassified" 3 0 0)
                                    ( ("otu_2199" 3 0 0)
                                    )
                                )
                            )
                        )
                    )
                    ( ("Oxalobacteraceae" 11 7 0)
                        ( ("Unclassified" 6 1 0)
                            ( ("otu_2252" 6 1 0)
                            )
                        )
                        ( ("Janthinobacterium" 5 6 0)
                            ( ("Unclassified" 4 1 0)
                                ( ("otu_2256" 4 1 0)
                                )
                            )
                            ( ("Duganella" 1 5 0)
                                ( ("Aquaspirillum_arcticum" 0 2 0)
                                    ( ("otu_2258" 0 2 0)
                                    )
                                )
                                ( ("Unclassified" 1 3 0)
                                    ( ("otu_2257" 1 3 0)
                                    )
                                )
                            )
                        )
                    )
                    ( ("bacterium_Ellin6067" 16 15 0)
                        ( ("Unclassified" 2 1 0)
                            ( ("otu_2192" 2 1 0)
                            )
                        )
                        ( ("AKYH1344" 14 14 0)
                            ( ("otu_2193" 14 14 0)
                            )
                        )
                    )
                )
                ( ("MND1" 24 32 0)
                    ( ("mle1-7" 1 3 0)
                        ( ("otu_2280" 1 3 0)
                        )
                    )
                    ( ("LO131" 10 6 0)
                        ( ("otu_2279" 10 6 0)
                        )
                    )
                    ( ("Unclassified" 13 23 0)
                        ( ("otu_2278" 13 23 0)
                        )
                    )
                )
            )
            ( ("Xanthomonadales" 18 4 0)
                ( ("Rhodanobacter" 0 1 0)
                    ( ("Unclassified" 0 1 0)
                        ( ("otu_2526" 0 1 0)
                        )
                    )
                )
                ( ("Unclassified" 5 2 0)
                    ( ("otu_2517" 5 2 0)
                    )
                )
                ( ("KD8-72" 13 1 0)
                    ( ("otu_2520" 13 1 0)
                    )
                )
            )
        )
    )
    ( ("Actinobacteria" 77 107 0)
        ( ("Coriobacteridae" 3 0 0)
            ( ("Unclassified" 3 0 0)
                ( ("otu_350" 3 0 0)
                )
            )
        )
        ( ("a13143" 2 18 0)
            ( ("Elev_16S_1052" 0 13 0)
                ( ("Elev_16S_575" 0 13 0)
                    ( ("otu_237" 0 13 0)
                    )
                )
            )
            ( ("Unclassified" 2 5 0)
                ( ("otu_235" 2 5 0)
                )
            )
        )
        ( ("Rubrobacteridae" 21 28 0)
            ( ("Unclassified" 1 0 0)
                ( ("otu_370" 1 0 0)
                )
            )
            ( ("Thermoleiphilaceae" 3 18 0)
                ( ("Unclassified" 0 5 0)
                    ( ("otu_374" 0 5 0)
                    )
                )
                ( ("C-F-2" 3 13 0)
                    ( ("MFC-EB10" 3 13 0)
                        ( ("otu_376" 3 13 0)
                        )
                    )
                )
            )
            ( ("MC47" 17 10 0)
                ( ("otu_371" 17 10 0)
                )
            )
        )
        ( ("Acidimicrobidae" 21 34 0)
            ( ("Unclassified" 0 3 0)
                ( ("otu_238" 0 3 0)
                )
            )
            ( ("Microthrixineae" 4 2 0)
                ( ("Unclassified" 4 2 0)
                    ( ("otu_257" 4 2 0)
                    )
                )
            )
            ( ("Acidimicrobineae" 2 2 0)
                ( ("RCP2-2" 1 0 0)
                    ( ("otu_243" 1 0 0)
                    )
                )
                ( ("Unclassified" 1 2 0)
                    ( ("otu_240" 1 2 0)
                    )
                )
            )
            ( ("CL500-29" 2 8 0)
                ( ("Unclassified" 2 8 0)
                    ( ("otu_247" 2 8 0)
                    )
                )
            )
            ( ("a13110" 3 5 0)
                ( ("otu_239" 3 5 0)
                )
            )
            ( ("EB1017_group" 10 14 0)
                ( ("FAC31" 4 9 0)
                    ( ("otu_251" 4 9 0)
                    )
                )
                ( ("Unclassified" 6 5 0)
                    ( ("otu_250" 6 5 0)
                    )
                )
            )
        )
        ( ("Actinobacteridae" 30 27 0)
            ( ("Propionibacterineae" 1 3 0)
                ( ("Nocardioidaceae" 1 3 0)
                    ( ("Unclassified" 1 3 0)
                        ( ("otu_339" 1 3 0)
                        )
                    )
                )
            )
            ( ("Intrasporangiaceae" 4 1 0)
                ( ("Intrasporangiaceae" 4 1 0)
                    ( ("Unclassified" 4 1 0)
                        ( ("otu_311" 4 1 0)
                        )
                    )
                )
            )
            ( ("Micromonosporaceae" 3 3 0)
                ( ("Unclassified" 3 3 0)
                    ( ("otu_333" 3 3 0)
                    )
                )
            )
            ( ("Streptosporangineae" 1 0 0)
                ( ("Unclassified" 1 0 0)
                    ( ("otu_346" 1 0 0)
                    )
                )
            )
            ( ("Frankineae" 2 4 0)
                ( ("Geodermatophilaceae" 0 2 0)
                    ( ("otu_305" 0 2 0)
                    )
                )
                ( ("Unclassified" 2 2 0)
                    ( ("otu_304" 2 2 0)
                    )
                )
            )
            ( ("Corynebacterineae" 4 7 0)
                ( ("Mycobacteriaceae" 4 7 0)
                    ( ("Unclassified" 4 7 0)
                        ( ("otu_294" 4 7 0)
                        )
                    )
                )
            )
            ( ("Micrococcaceae" 5 6 0)
                ( ("Unclassified" 0 1 0)
                    ( ("otu_324" 0 1 0)
                    )
                )
                ( ("AKAU3652" 1 0 0)
                    ( ("otu_325" 1 0 0)
                    )
                )
                ( ("Arthrobacter" 4 5 0)
                    ( ("Micrococcus" 0 2 0)
                        ( ("Actinomycetales" 0 2 0)
                            ( ("Unclassified" 0 2 0)
                                ( ("otu_328" 0 2 0)
                                )
                            )
                        )
                    )
                    ( ("Unclassified" 4 3 0)
                        ( ("otu_326" 4 3 0)
                        )
                    )
                )
            )
            ( ("Streptomycineae" 3 2 0)
                ( ("otu_345" 3 2 0)
                )
            )
            ( ("Unclassified" 2 1 0)
                ( ("otu_261" 2 1 0)
                )
            )
            ( ("Cellulomonadaceae" 1 0 0)
                ( ("Cellulomonas" 1 0 0)
                    ( ("Unclassified" 1 0 0)
                        ( ("otu_281" 1 0 0)
                        )
                    )
                )
            )
            ( ("Kineosporiaceae" 4 0 0)
                ( ("Unclassified" 4 0 0)
                    ( ("otu_313" 4 0 0)
                    )
                )
            )
        )
    )
    ( ("AD3" 36 7 0)
        ( ("JG37-AG-4" 4 0 0)
            ( ("JG30-KF-C12" 4 0 0)
                ( ("JG30-KF-A11" 4 0 0)
                    ( ("otu_382" 4 0 0)
                    )
                )
            )
        )
        ( ("ABS-6" 32 7 0)
            ( ("otu_379" 32 7 0)
            )
        )
    )
    ( ("Acidobacteria" 312 221 0)
        ( ("Sva0725" 0 1 0)
            ( ("otu_232" 0 1 0)
            )
        )
        ( ("RB25" 0 6 0)
            ( ("Unclassified" 0 2 0)
                ( ("otu_223" 0 2 0)
                )
            )
            ( ("JG37-AG-81" 0 4 0)
                ( ("otu_224" 0 4 0)
                )
            )
        )
        ( ("Unclassified" 1 2 0)
            ( ("otu_182" 1 2 0)
            )
        )
        ( ("TM1" 1 0 0)
            ( ("otu_233" 1 0 0)
            )
        )
        ( ("ABS-327" 15 5 0)
            ( ("Unclassified" 2 0 0)
                ( ("otu_183" 2 0 0)
                )
            )
            ( ("EB1093" 13 5 0)
                ( ("otu_184" 13 5 0)
                )
            )
        )
        ( ("Acidobacteria-5" 1 3 0)
            ( ("JG37-AG-149" 1 3 0)
                ( ("otu_199" 1 3 0)
                )
            )
        )
        ( ("Acidobacteria-6" 36 51 0)
            ( ("RB40" 4 0 0)
                ( ("otu_204" 4 0 0)
                )
            )
            ( ("iii1-15" 22 40 0)
                ( ("ii3-15" 1 7 0)
                    ( ("Riz6I" 1 7 0)
                        ( ("otu_203" 1 7 0)
                        )
                    )
                )
                ( ("Unclassified" 21 33 0)
                    ( ("otu_201" 21 33 0)
                    )
                )
            )
            ( ("Unclassified" 10 11 0)
                ( ("otu_200" 10 11 0)
                )
            )
        )
        ( ("iii1-8" 2 1 0)
            ( ("DS-18" 0 1 0)
                ( ("otu_221" 0 1 0)
                )
            )
            ( ("Unclassified" 2 0 0)
                ( ("otu_220" 2 0 0)
                )
            )
        )
        ( ("CCU21" 1 4 0)
            ( ("otu_217" 1 4 0)
            )
        )
        ( ("Acidobacteria-2" 27 7 0)
            ( ("WD2123" 2 1 0)
                ( ("otu_189" 2 1 0)
                )
            )
            ( ("Unclassified" 1 0 0)
                ( ("otu_185" 1 0 0)
                )
            )
            ( ("CLi114" 10 2 0)
                ( ("JG36-TzT-77" 10 2 0)
                    ( ("otu_187" 10 2 0)
                    )
                )
            )
            ( ("Ellin5121" 14 4 0)
                ( ("otu_188" 14 4 0)
                )
            )
        )
        ( ("Acidobacteria-4" 17 57 0)
            ( ("UA12" 1 6 0)
                ( ("Unclassified" 0 1 0)
                    ( ("otu_196" 0 1 0)
                    )
                )
                ( ("Elev_16S_623" 1 5 0)
                    ( ("otu_197" 1 5 0)
                    )
                )
            )
            ( ("Unclassified" 10 31 0)
                ( ("otu_190" 10 31 0)
                )
            )
            ( ("Ellin6075" 3 4 0)
                ( ("Unclassified" 3 4 0)
                    ( ("otu_193" 3 4 0)
                    )
                )
            )
            ( ("A08_WMSP1" 3 16 0)
                ( ("otu_191" 3 16 0)
                )
            )
        )
        ( ("Acidobacteriales" 120 38 0)
            ( ("Acidobacteriaceae" 120 38 0)
                ( ("Ephadobacter" 3 9 0)
                    ( ("UA1" 0 2 0)
                        ( ("otu_214" 0 2 0)
                        )
                    )
                    ( ("Unclassified" 3 7 0)
                        ( ("otu_211" 3 7 0)
                        )
                    )
                )
                ( ("Ellin323" 117 29 0)
                    ( ("Amb_16S_521" 29 2 0)
                        ( ("Unclassified" 0 2 0)
                            ( ("otu_209" 0 2 0)
                            )
                        )
                        ( ("Amb_16S_458" 29 0 0)
                            ( ("otu_210" 29 0 0)
                            )
                        )
                    )
                    ( ("Uncl." 88 27 0)  ; Unclassified
                        ( ("otu_208" 88 27 0)
                        )
                    )
                )
            )
        )
        ( ("Solibacteres" 91 46 0)
            ( ("Unclassified" 31 22 0)
                ( ("otu_227" 31 22 0)
                )
            )
            ( ("Solibacterales" 60 24 0)
                ( ("B74" 1 4 0)
                    ( ("otu_229" 1 4 0)
                    )
                )
                ( ("bacterium_Ellin6071" 1 5 0)
                    ( ("otu_230" 1 5 0)
                    )
                )
                ( ("Unclassified" 58 15 0)
                    ( ("otu_228" 58 15 0)
                    )
                )
            )
        )
    )
)
)
