 (define top_hsb_vals
   '(
     ("Proteobacteria"                         1    0.0   0.65  0.93)
     ("Acidobacteria"                          2    0.08 0.75  0.98)
     ("Actinobacteria"                         3    0.175 0.9  0.95)
     ("Verrucomicrobia"                        4    0.25  0.7  0.9)
     ("SPAM"                                   5    0.4   0.7  0.85 )
     ("Bacteroidetes"                          6    0.55  0.7  0.9)
     ("Planctomycetes"                         7    0.7  0.5   0.9)
     ("AD3"                                    8    0.85  0.5  0.9)
     ("Gemmatimonadetes"                       9    0.3   0.5  1.0)
     ("Chloroflexi"                           10    1.0   0.4  1.0)
     ("Firmicutes"                            11    0.475 0.4  0.7)
     ("Nitrospirae"                           12    1.0   0.4  1.0)
     ("ZB2"                                   13    0.575 0.4  1.0)
     ("OD2"                                   14    0.75  0.4  0.725)
     ("Cyanobacteria"                         15    0.400 0.6  1.0)
     ("Chlorobi"                              16    0.175 0.6  1.0)
     ("TM7"                                   17    0.175 0.6  1.0)
     ("OP11"                                  18    0.175 0.6  1.0)
     ("WS3"                                   19    0.12 0.6  1.0)
     ("TM6"                                   20    0.06 0.6  1.0)

     ("SBR1093"                               21    0.175 0.6  1.0)
     ("Elusimicrobia"                         22    0.4   0.5  0.55 )
     ("ZB2"                                   23    0.4   0.5  0.55 )
     ("OP10"                                  24    0.175 0.6  1.0)
     ("SC4"                                   25    0.175 0.6  1.0)
     ("OP3"                                   26    0.4   0.5  0.55 )
     ("Elev_16S_1860"                         27    0.175 0.6  1.0)
    ))

(show-label "SPAM")
(show-label "AD3")
(show-label "Chloroflexi")
(show-label "ZB2")
(show-label "OD2")
;(show-label "TM6")
;(show-label "SBR1093")
;(show-label "Elusimicrobia")
;(show-label "SC4")
;(show-label "OP3")
;(show-label "Elev_16S_1860")

(set! font_size 10) ;12 ;13
(set! annulus_radius 34)  ; 36

(show-label "Acidobacteria")
(show-label "Acidobacteria")
(show-label "Acidobacterium")
(show-label "Actinobacteria")
(show-label "Actinobacteria")
(show-label "Arthrobacter")
(show-label "Mycobacterium")
(show-label "Thermobispora")
(show-label "Sporichthya")
;(show-label "Streptomyces")
(show-label "Bacteroidetes")
;(show-label "Flavobacteria")
(show-label "Flavobacterium")
(show-label "Sphingobacteria")
(show-label "Chitinophaga")
(show-label "Firmicutes")
(show-label "Bacilli")
(show-label "Bacillus")
(show-label "Thermobacillus")
(show-label "Clostridia")
(show-label "Desulfotomaculum")
(show-label "Genera_incertae_sedis")
(show-label "TM7")
(show-label "WS3")
(show-label "1145.8")
(show-label "Planctomycetes")
(show-label "Planctomycetacia")
(show-label "Gemmata")
(show-label "Pirellula")
(show-label "Proteobacteria")
(show-label "Alphaproteobacteria")
(show-label "Bradyrhizobium")
(show-label "Hyphomicrobium")
(show-label "Rhodoplanes")
(show-label "Rhizobium")
(show-label "Betaproteobacteria")
(show-label "Deltaproteobacteria")
(show-label "Acidovorax")
(show-label "Duganella")
(show-label "Oxalobacter")
(show-label "Azonexus")
(show-label "Verrucomicrobia")
(show-label "Verrucomicrobiae")
(show-label "Prosthecobacter")
(show-label "Verrucomicrobium")
(show-label "Gemmatimonadetes")
(show-label "Ellin323")
(show-label "Ellin329")
(show-label "Ellin314")
(show-label "Sphingomonadales")
;(show-label "AKYG694")   ; zero in amb
(show-label "Gitt-KF-194")
(show-label "Xanthomonadales")

(veto-label "Unclassified" 2)

(veto-label "Verrucomicrobiae" 1)
(veto-label "Planctomycetacia" 1)

(veto-label "Acidobacteria" 1)
(veto-label "Acidobacteriales" 1)
(veto-label "Acidobacteriaceae" 1)
(veto-label "Gemmatimonadetes" 1)
(veto-label "Gemmatimonadales" 2)
(veto-label "Gemm-1b" 2)
(veto-label "N1423WL" 3)
(veto-label "Sphingobacteria" 1)

(veto-label "TM7-1" 1)
(veto-label "Elev 16S 424" 2)

(veto-label "ABS-6" 1)
(veto-label "otu 379" 2)
(veto-label "Spartobacteria" 1)
(set-c-offsets "Deltaproteobacteria" '(0 0) 'cent)

(veto-label "SM2F11" 1)
(veto-label "KNA6-NB23" 2)
(veto-label "Elev_16S_1084" 3)
(veto-label "Elev_16S_1619" 4)

(veto-label "Anaerolineae" 1)
(veto-label "Bljii12" 1)
(veto-label "TK17" 1)
(veto-label "Chloroflexi-4" 1)
(veto-label "EB1097" 2)
(veto-label "S085" 2)
(veto-label "B07_WMSP1" 3)
(veto-label "SBR1031" 3)
(veto-label "SOGA31" 2)
(veto-label "otu-853" 4)
(veto-label "Ellin5121" 2)
(veto-label "CLi114" 2)
(veto-label "EB1093" 2)
(veto-label "MC47" 2)
(veto-label "JG37-AG-121" 1)
(veto-label "JG34-KF-252" 2)
(veto-label "C-F-2" 3)
(veto-label "MFC_EB10" 4)
(veto-label "Terrimonaceae" 2)

(veto-label "Elev 16S 1052" 2)
(veto-label "Elev 16S 575" 3)
(veto-label "Bljii12" 1)
(veto-label "EB1097"  2)
(veto-label "B07 WMSP1" 3)

(veto-label "Sediment-1" 1)
(veto-label "PRR-12" 2)
(veto-label "otu_2862" 3)

(set-c-offsets "Rhodoplanaceae"   '(0 0) 'cent)
(set-c-offsets "Bradyrhizobiales" '(0 0) 'cent)
(set-c-offsets "Bradyrhizobium" '(0 0) 'cent)

(set! radial_label_thresh 20)
(set! connect_label_thresh 3)

(set-c-offsets "Unclassified" '(0 -2) 'cent)

(set-c-offsets "Betaproteobacteria" '(40 0) 'cent)

(set-c-offsets "Uncl." '(0 -2) 'cent)

(set-c-offsets "Comamonadaceae" '(0 0) 'cent)

(if (eq? quant  elev-quant) 
    (begin
       (set-c-offsets "Uncl." '(0 -1) 'cent)
       (set-c-offsets "Bradyrhizobium" '(0 -1) 'cent)
       (set-c-offsets "TM7" '(0 0) 'cent)
       (set-c-offsets "AD3" '(0 0) 'cent)
       (set-c-offsets "Betaproteobacteria" '(0 0) '(0 4))
       (set-c-offsets "Bacteroidetes" '(0 -1) 'cent)
       (set-c-offsets "Gemmatimonadetes" '(0 0) 'cent)
       (set-c-offsets "Verrucomicrobia" '(0 -2) 'cent)
       (set-c-offsets "otu-2826" '(0 2) '(0 0))
       (set-c-offsets "Actinobacteria" '(0 0) '(0 18))
       (set-c-offsets "Ellin329" '(0 0) '(0 -3))
       (set-c-offsets "otu 1908" '(0 0) 'cent)
       (set-c-offsets "Burkholderiales" '(0 0) 'cent)
       (set-c-offsets "Solibacteres" '(0 0) 'cent)
       (set-c-offsets "Solibacterales" '(0 0) '(0 -1))
       (set-c-offsets "Acidobacteria" '(0 1) '(0 0))
       (set-c-offsets "A08 WMSP1" '(0 -1) '(0 0))
       (set-c-offsets "Actinobacteridae" '(0 1) '(0 1))
       (set-c-offsets "Rubrobacteridae" '(0 -1) '(0 -1))
       (set-c-offsets "otu 371" '(0 0) '(0 0))
       (set-c-offsets "Thermoleiphilaceae" '(0 0) '(0 -1))
       (set-c-offsets "Acidimicrobidae" '(0 0) 'cent)
       (set-c-offsets "Gemmata" '(0 1) '(0 0))
       (set-c-offsets "otu 868" '(0 0) 'cent)
       (set-c-offsets "Chloroflexi" '(0 0) 'cent)
       (set-c-offsets "Firmicutes" '(0 0) 'cent)
       (set-c-offsets "Bacilli" '(0 -1) '(0 0))
       (set-c-offsets "Elev 16S 1860" '(0 2) 'cent)
       (set-c-offsets "otu 986" '(0 -1) 'cent)
       (set-c-offsets "ZB2" '(0 1) 'cent)
      )  ;  ambient
     (begin
       (set-c-offsets "Uncl." '(0 -2) 'cent)
       (set-c-offsets "Bradyrhizobium" '(0 0) 'cent)
       (set-c-offsets "TM7" '(0 0) 'cent)
       (set-c-offsets "AD3" '(0 0) 'cent)
       (set-c-offsets "Myxococcales" '(0 -2) 'cent)
       (set-c-offsets "Betaproteobacteria" '(40 0) '(0 2))
       (set-c-offsets "Bacteroidetes" '(0 0) 'cent)
       (set-c-offsets "Verrucomicrobia" '(0 0) '(0 3))
       (set-c-offsets "Actinobacteria" '(0 0) 'cent)
       (set-c-offsets "Actinobacteridae" '(0 1) 'cent)
       (set-c-offsets "Rubrobacteridae" '(0 0) '(0 -1))
       (set-c-offsets "Acidimicrobidae" '(0 1) 'cent)
       (set-c-offsets "Burkholderiales" '(0 0) '(0 -4))
       (set-c-offsets "Xanthomonadales" '(0 0) '(0 -2))
       (set-c-offsets "MND1" '(0 0) 'cent)
       (set-c-offsets "KD8-72" '(0 0) 'cent)
       (set-c-offsets "Amb 16S 521" '(0 0) 'cent)
       (set-c-offsets "Acidobacteria-6" '(0 0) '(0 -1))
       (set-c-offsets "Acidobacteria-2" '(0 -1) '(0 0))
       (set-c-offsets "JG36-TzT-77" '(0 -1) 'cent)
       (set-c-offsets "otu 190" '(0 2) '(0 0))
       (set-c-offsets "A08_WMSP1" '(0 -2) '(0 0))
       (set-c-offsets "otu 371" '(0 0) '(0 1))
       (set-c-offsets "Saprospirales" '(0 -1) '(0 0))
       (set-c-offsets "SPAM" '(0 -1) 'cent)
       (set-c-offsets "Gemmata" '(0 3) '(0 0))
       (set-c-offsets "otu 1664" '(0 0) '(0 -2))
       (set-c-offsets "otu 1656" '(0 0) 'cent)
       (set-c-offsets "Gemmatimonadetes" '(0 0) 'cent)
       (set-c-offsets "Firmicutes" '(0 0) 'cent)
       (set-c-offsets "Bacilli" '(0 -1) '(0 0))
       (set-c-offsets "WS3"     '(40 0) 'cent)

     )
)