(define amb_recs '(
  (1 "AY357262" ("Fungi" "Ascomycota" "mitosporic Ascomycota" "Anguillospora") )
  (1 "AJ496240" ("Fungi" "Ascomycota" "mitosporic Ascomycota" "Hyphozyma") )
  (5 "U04233" ("Fungi" "Ascomycota" "Pezizomycotina" "Dothideomycetes" "Pleosporales" "Leptosphaeriaceae" "Leptosphaeria" "Leptosphaeria") )
  (26 "U42666" ("Fungi" "Ascomycota" "Pezizomycotina" "Pezizomycetes" "Pezizales" "Pezizaceae" "Cazia") )
  (1 "AF054899" ("Fungi" "Ascomycota" "Pezizomycotina" "Pezizomycetes" "Pezizales" "Pezizaceae" "Pachyphloeus") )
  (10 "AF287835" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Cortinariaceae" "Inocybe") )
  (8 "AY665780" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Schizophyllaceae" "Grifola") )
  (33 "AF287838" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Tricholomataceae" "Laccaria") )
  (4 "AJ496255" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Tricholomataceae" "mitosporic Tricholomataceae" "Asterophora") )
  (1 "AY771599" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Tricholomataceae" "Rickenella") )
  (1 "U09535" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Agaricales" "Tricholomataceae" "unclassified Tricholomataceae") )
  (1 "AF518586" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Aphyllophorales" "Corticiaceae" "Punctularia") )
  (1 "AY705969" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Aphyllophorales" "Ganodermataceae" "Ganoderma") )
  (15 "AY278769" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Boletales" "Boletineae" "Boletaceae" "Boletus") )
  (1 "AY757266" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Ceratobasidiales" "Ceratobasidiaceae" "Ceratobasidium") )
  (10 "AY946268" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Ceratobasidiales" "Ceratobasidiaceae" "Thanatephorus") )
  (3 "AY771601" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Phallales" "Phallaceae" "Phallus") )
  (18 "AF026627" ("Fungi" "Basidiomycota" "Hymenomycetes" "Homobasidiomycetes" "Thelephorales" "Thelephoraceae" "Thelephora") )
  (9 "AY766081" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Heterobasidiomycetidae" "Sebacinales" "Sebacinaceae" "Tremellodendron") )
  (1 "AB032665" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Tremellomycetidae" "Cystofilobasidiales" "Cystofilobasidiaceae" "Mrakia") )
  (7 "AB075546" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Tremellomycetidae" "Filobasidiales" "Filobasidiaceae" "Filobasidium") )
  (10 "AB032649" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Tremellomycetidae" "Filobasidiales" "mitosporic Filobasidiales" "Cryptococcus") )
  (2 "AB032645" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Tremellomycetidae" "Tremellales" "mitosporic Tremellales" "Cryptococcus") )
  (12 "AB035587" ("Fungi" "Basidiomycota" "Hymenomycetes" "Heterobasidiomycetes" "Tremellomycetidae" "Trichosporonales" "Cryptococcus") )
  (8 "AB126647" ("Fungi" "Basidiomycota" "Urediniomycetes" "Erythrobasidium clade" "Rhodotorula") )
  (1 "AY123323" ("Fungi" "Basidiomycota" "Urediniomycetes" "Urediniomycetidae" "Platygloeales" "Eocronartiaceae" "Eocronartium") )
  (9 "AY601710" ("Fungi" "Chytridiomycota" "Chytridiales" "Chytridiaceae" "Rhizophydium") )
  (1 "AF164245" ("Fungi" "Chytridiomycota" "Spizellomycetales" "Olpidiaceae" "Powellomyces") )
  (2 "AF164247" ("Fungi" "Chytridiomycota" "Spizellomycetales" "Spizellomycetaceae" "Gaertneriomyces") )
  (8 "AJ276081" ("Fungi" "Glomeromycota" "Glomeromycetes" "Paraglomerales" "Paraglomeraceae" "Paraglomus") )
  (2 "AF368504" ("Fungi" "Zygomycota" "Zygomycetes" "Entomophthorales" "Basidiobolaceae" "Basidiobolus") )
  (59 "AF157143" ("Fungi" "Zygomycota" "Zygomycetes" "Mortierellales" "Mortierellaceae" "Mortierella") )
  (1 "AF457127" ("Alveolata" "Apicomplexa" "Gregarinia" "Eugregarinida" "Monocystidae" "Monocystis") )
  (11 "M97908" ("Alveolata" "Ciliophora" "Colpodea" "Colpodida" "Colpodidae" "Colpoda") )
  (4 "AF060452" ("Alveolata" "Ciliophora" "Colpodea" "Cyrtolophosidida" "Grossglockneriidae" "Pseudoplatyophrya") )
  (1 "AF060454" ("Alveolata" "Ciliophora" "Colpodea" "Cyrtolophosidida" "Woodruffiidae" "Platyophrya") )
  (6 "AY297715" ("Alveolata" "Ciliophora" "Oligohymenophorea" "Scuticociliatia" "Philasterida" "Philasteridae" "Paralembus") )
  (5 "AF300282" ("Alveolata" "Ciliophora" "Phyllopharyngea" "Cyrtophorida" "Chilodonella") )
  (20 "AJ310493" ("Alveolata" "Ciliophora" "Spirotrichea" "Stichotrichia" "Stichotrichida" "Oxytrichidae" "Gonostomum") )
  (8 "AY498654" ("Alveolata" "Ciliophora" "Spirotrichea" "Stichotrichia" "Stichotrichida" "Oxytrichidae" "Orthamphisiella") )
  (1 "AF080096" ("Alveolata" "Dinophyceae" "Blastodiniales" "Oodiniaceae" "Amyloodinium") )
  (8 "AF411276" ("Cercozoa" "Cercomonadida" "Bodomorpha") )
  (26 "AY496047" ("Cercozoa" "Cercomonadida" "Cercomonadidae" "Cercomonas") )
  (1 "AY496048" ("Cercozoa" "Cercomonadida" "Cercomonadidae" "Neocercomonas") )
  (1 "AF411280" ("Cercozoa" "Cercomonadida" "Spongomonas") )
  (2 "X77692" ("Cercozoa" "Euglyphida" "Euglyphidae" "Euglypha") )
  (10 "AJ418792" ("Cercozoa" "Euglyphida" "Trinematidae" "Trinema") )
  (8 "AY496043" ("Cercozoa" "Heteromitidae" "Heteromita") )
  (7 "AJ514867" ("Cercozoa" "Lecythium") )
  (10 "AF411259" ("Cercozoa" "Thaumatomonadida" "Thaumatomastigidae" "Thaumatomonas") )
  (1 "AJ535147" ("stramenopiles" "Bacillariophyta" "Bacillariophyceae" "Bacillariophycidae" "Thalassiophysales" "Catenulaceae" "Amphora") )
  (1 "AY485470" ("stramenopiles" "Bacillariophyta" "Coscinodiscophyceae" "Rhizosoleniophycidae" "Rhizosoleniales" "Rhizosoleniaceae" "Proboscia") )
  (2 "AF243501" ("stramenopiles" "Bicosoecida" "Adriamonas") )
  (3 "AF123301" ("stramenopiles" "Chrysophyceae" "Ochromonadales" "Ochromonadaceae" "Epipyxis") )
  (1 "AB023070" ("stramenopiles" "Chrysophyceae" "Ochromonadales" "Ochromonadaceae" "Poterioochromonas") )
  (4 "AJ236862" ("stramenopiles" "Chrysophyceae" "Ochromonadales" "Ochromonadaceae" "Spumella") )
  (6 "AY295674" ("stramenopiles" "environmental samples") )
  (1 "AY872266" ("stramenopiles" "Labyrinthulida" "Thraustochytriidae") )
  (2 "AJ238663" ("stramenopiles" "Oomycetes" "Leptomitales" "Apodachlya") )
  (36 "AJ238653" ("stramenopiles" "Oomycetes" "Pythiales" "Pythiaceae" "Pythium") )
  (2 "AJ579339" ("stramenopiles" "Xanthophyceae" "Mischococcales" "Botryidiopsidaceae" "Botrydiopsis") )
  (7 "AB183637" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Chlamydomonadales" "Chlamydomonadaceae" "Brachiomonas") )
  (10 "AY220083" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Chlamydomonadales" "Chlamydomonadaceae" "Chlamydomonad") )
  (5 "AF367859" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Chlamydomonadales" "Chlamydomonadales incertae sedis" "Heterochlamydomonas") )
  (8 "AF514407" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Chlorococcales" "Chlorococcaceae" "Chlorococcum") )
  (3 "AY377440" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Gloeocystis") )
  (5 "AY195984" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Sphaeropleales" "Hydrodictyaceae" "unclassified Hydrodictyaceae") )
  (13 "AB055800" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Sphaeropleales" "Scenedesmaceae" "Coelastrella") )
  (1 "AB012847" ("Viridiplantae" "Chlorophyta" "Chlorophyceae" "Sphaeropleales" "Scenedesmaceae" "Scotiellopsis") )
  (10 "X63505" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Chlorella") )
  (1 "AB017435" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Coenocystis") )
  (5 "AB055866" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Microthamniales" "Stichococcus") )
  (6 "AB080310" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Microthamniales" "Trebouxia") )
  (1 "AB012845" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Muriella") )
  (10 "z28971" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Myrmecia") )
  (2 "AY422078" ("Viridiplantae" "Chlorophyta" "Trebouxiophyceae" "Paradoxia") )
  (8 "AJ243348" ("Viridiplantae" "Streptophyta" "Embryophyta" "Bryophyta" "Bryopsida" "Bryidae" "Bryales" "Bryaceae" "Bryum") )
  (4 "Y08989" ("Viridiplantae" "Streptophyta" "Embryophyta" "Bryophyta" "Bryopsida" "Dicranidae" "Dicranales" "Ditrichaceae" "Ceratodon") )
  (20 "X89874" ("Viridiplantae" "Streptophyta" "Embryophyta" "Bryophyta" "Bryopsida" "Dicranidae" "Dicranales" "Dicranaceae" "Dicranum") )
  (3 "AF023681" ("Viridiplantae" "Streptophyta" "Embryophyta" "Bryophyta" "Bryopsida" "Dicranidae" "Seligeriales" "Seligeriaceae" "Blindia") )
  (7 "X78889" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Moniliformopses" "Filicophyta" "Filicopsida" "Filicales" "Adiantaceae" "Adiantum") )
  (5 "AB088026" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "eudicotyledons" "Apiales" "Araliaceae" "Panax") )
  (35 "AF107576" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Asterales" "Asteraceae" "Mutisioideae" "Mutisieae" "Gerbera") )
  (1 "AJ236008" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Asterales" "Goodeniaceae" "Scaevola") )
  (5 "U66701" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Dipsacales" "Caprifoliaceae" "Lonicera") )
  (1 "AF207027" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Caryophyllales" "Caryophyllaceae" "Stellaria") )
  (5 "AF206908" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Caryophyllales" "Phytolaccaceae" "Ercilla") )
  (2 "U42426" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Cucurbitales" "Datiscaceae" "Datisca") )
  (55 "AJ011011" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Fabales" "Fabaceae" "Papilionoideae" "Cicereae" "Cicer") )
  (1 "AF525695" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Fabales" "Fabaceae" "Papilionoideae" "Phaseoleae" "Mucuna") )
  (22 "AF071069" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Fabales" "Fabaceae" "Papilionoideae" "Trifolieae" "Trifolium") )
  (1 "AF223066" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Rosales" "Cannabaceae" "Humulus") )
  (2 "AF168855" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Liliopsida" "Poales" "Joinvilleaceae" "Joinvillea") )
  (5 "AJ272181" ("Viridiplantae" "Streptophyta" "Embryophyta" "Tracheophyta" "Spermatophyta" "Magnoliophyta" "Liliopsida" "Poales" "Poaceae" "Pooideae" "Triticeae" "Triticum") )
  (1 "AJ553921" ("Viridiplantae" "Streptophyta" "Zygnemophyceae" "Desmidiales" "Gonatozygaceae" "Gonatozygon") )
  (1 "AF087128" ("Rhodophyta" "Bangiophyceae" "Erythropeltidales" "Compsopogonaceae" "Compsopogon") )
  (1 "AF310898" ("Plasmodiophorida" "Plasmodiophoridae" "Polymyxa") )
  (1 "AF022025" ("Metazoa" "Arthropoda" "Chelicerata" "Arachnida" "Acari" "Acariformes" "Sarcoptiformes" "Oribatida" "Desmonomata" "Trhypochthoniidae" "Allonothrus") )
  (6 "Z26765" ("Metazoa" "Arthropoda" "Hexapoda" "Collembola" "Arthropleona" "Poduroidea" "Hypogastruridae" "Hypogastrura") )
  (1 "AY555522" ("Metazoa" "Arthropoda" "Hexapoda" "Collembola" "Symphypleona" "Katiannidae" "Sminthurinus") )
  (1 "AF250103" ("Metazoa" "Arthropoda" "Hexapoda" "Insecta" "Pterygota" "Neoptera" "Endopterygota" "Coleoptera" "Curculionidae" "Molytinae" "Hylobiini" "Pachylobius") )
  (16 "AY593937" ("Metazoa" "Nematoda" "Chromadorea" "Monhysterida" "Monhysteridae" "Eumonhystera") )
  (1 "AJ875155" ("Metazoa" "Nematoda" "Enoplea" "Dorylaimida" "Dorylaimina" "Dorylaimoidea" "Aporcelaimidae" "Aporcelaiminae" "Aporcelaimellus") )
  (1 "AY284788" ("Metazoa" "Nematoda" "Enoplea" "Dorylaimida" "Dorylaimina" "Dorylaimoidea" "Nordiidae" "Pungentinae" "Pungentus") )
  (2 "AY284834" ("Metazoa" "Nematoda" "Enoplea" "Dorylaimida" "Dorylaimina" "Tylencholaimoidea" "Tylencholaimidae" "Tylencholaiminae" "Tylencholaimus") )
  (12 "AY284727" ("Metazoa" "Nematoda" "Enoplea" "Enoplida" "Tripyloidea" "Prismatolaimidae" "Prismatolaimus") )
  (16 "AJ439583" ("Metazoa" "Nematoda" "Enoplea" "Triplonchida" "Diphtherophorina" "Trichodoroidea" "Trichodoridae" "Trichodorus") )
  (9 "U70081" ("Metazoa" "Platyhelminthes" "Turbellaria" "Rhabdocoela" "Typhloplanoida" "Typhloplanidae" "Rhynchomesostominae" "Mesocastrada") )
  (1 "AY582119" ("Metazoa" "Tardigrada" "Heterotardigrada" "Echiniscidae" "Pseudechiniscus") )
  (11 "AY183891" ("Lobosea" "Euamoebida" "Vexilliferidae" "Vexillifera") )
  (1 "AY294144" ("Lobosea" "Euamoebida" "Vannellidae" "Platyamoeba") )
  (3 "AY549564" ("Lobosea" "Leptomyxida" "Flabellulidae" "Ripidomyxa") )
  (51 "AF290540" ("Cryothecomonas") )
  (8 "L37037" ("Apusomonadidae" "Apusomonas") )
  (3 "AF411284" ("Granuloreticulosea" "Athalamea" "Gymnophrys") )
  (8 "AJ130850" ("environmental samples") )
  (3 "AF084230" ("Choanoflagellida" "Codonosigidae" "Monosiga") )
  (1 "Z34900" ("Choanoflagellida" "Codonosigidae" "Sphaeroeca") )
  (3 "AF508269" ("Cryptophyta" "Cryptomonadaceae" "Chroomonas") )
  (8 "AY102615" ("Acanthamoebidae" "Acanthamoeba") )
  (1 "AY268042" ("Centroheliozoa" "Heterophryidae" "Chlamydaster") )
  (1 "AY336701" ("Eccrinales" "Eccrinaceae" "Enterobryus") )
) )
